export const ROUTE = {
  SIGN_IN: 'SignIn',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOME: 'HomeScreen',
  PROFILE: 'ProfileScreen',
  CATEGORIES: 'CategoriesScreen',
  SUB_CATEGORIES: 'SubCategoriesScreen',
  CHECKOUT: 'CheckoutScreen',
  ORDERS: 'OrdersScreen',
  ORDER_DETAIL: 'OrderDetailScreen',
  SEARCH: 'SearchScreen',
  ADMIN_DASHBOARD: 'Dashboard',
  CATEGORY: 'Category',
  SUB_CATEGORY: 'Sub Category',
  PRODUCT: 'Product',
};
